config/routes.rb
Rails.application.routes.draw do

  root :to=>"home#index"

   get "signed_out" => "authentication#signed_out"
   get "forgot_password" => "authentication#forgot_password"
   get "password_sent" => "authentication#password_sent"

   get "sign_in" => "authentication#sign_in"
   post "sign_in" => "authentication#login"

   get "new_user" => "authentication#new_user"
   post "new_user" => "authentication#register"

   get "account_settings" => "authentication#account_settings"
   put "account_settings" => "authentication#set_account_info"

   get "forgot_password" => "authentication#forgot_password"
   put "forgot_password" => "authentication#send_password_reset_instructions"
   get "password_reset" => "authentication#password_reset"
   put "password_reset" => "authentication#new_password"

   get "admin_users" => "admin#users"
   delete "user/:id" => "admin#delete_user", :as => "user"

  get "new_list" => "list#new"
  post "new_list" => "list#create"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Listler</title>
<%= stylesheet_link_tag "application", :media => "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
    <div id="wrapper">
        <nav class="navbar navbar-default navbar-fixed-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Listler</a>
            </div>
            <!-- /.navbar-header -->

            <ul class="nav navbar-top-links navbar-right">
                <% if current_user %>
                    <li><%= link_to "Sign Out", signed_out_path %></li>
                    <li><%= link_to "My account", account_settings_path %></li>
                <% else %>
                    <li><%= link_to "Sign up", new_user_path %></li>
                    <li><%= link_to "Sign In", sign_in_path %></li>
                <% end %>
            </ul>
            <!-- /.navbar-top-links -->
          <% if current_user %>
            <div class="navbar-default navbar-static-side" role="navigation">
                <div class="sidebar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                        <a href="/"><i class="fa fa-dashboard fa-fw"></i> Dashboard</a>
                        </li>
                    </ul>
                    <!-- /#side-menu -->
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
          <% end %>
        </nav>

      <%= yield %>
    </div>
    <!-- /.wrapper -->
</body>
</html>